apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  dataVolumeCapacity: 5Gi
  storageClass:
    name: managed-csi
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 500m
        memory: 1536Mi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: "c3.demo.local"
      port: 9021
  configOverrides:
    server:
      - confluent.controlcenter.internal.topics.replication=1
      - confluent.controlcenter.command.topic.replication=1
      - confluent.metrics.topic.replication=1
      - confluent.monitoring.interceptor.topic.replication=1
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
